name: 'Setup Kubeval cli action'
description: 'This Action setups kubeval cli'
inputs:
  version:  # id of input
    description: 'version of the cli'
    required: false
    default: 'latest'
runs:
  using: 'node16'
  main: 'dist/index.js'